### ISSUE TITLE
Protocols on GitHub.io

### ISSUE THREAD

**Issue by kenatcampbellmusclelab** [Campbell-Muscle-Lab/Protocols#1]
Utku,

Could you add a GitHub pages site that provides links to the documents please?

See [https://campbell-muscle-lab.github.io/howtos_GitHub/pages/github_pages/github_pages.html](https://campbell-muscle-lab.github.io/howtos_GitHub/pages/github_pages/github_pages.html)

Thanks

**Comment by utkugulbulak** [comment]
@kenatcampbellmusclelab  The site is deployed: https://campbell-muscle-lab.github.io/Protocols/. Please let me know if you'd like me to add or remove things.
